/**
 * Branded integrity-report PDF generator for SemanticGuard AI.
 *
 * Produces a professional, multi-candidate PDF using real database-driven
 * session + violation data. No mock data — every value passed in originates
 * from the recruiter integrity dashboard.
 */
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/* ─── Branding constants ────────────────────────────────────────────────────── */

const COMPANY_NAME = 'Semantic Services Rwanda';
const SYSTEM_NAME = 'SemanticGuard AI Integrity Report';
const LOGO_URL = '/logo-icon.png';

// Brand palette (RGB) mirrored from the app theme.
const NAVY: [number, number, number] = [15, 45, 82];
const BLUE: [number, number, number] = [74, 144, 226];
const SLATE: [number, number, number] = [100, 116, 139];
const RED: [number, number, number] = [220, 38, 38];
const AMBER: [number, number, number] = [202, 138, 4];
const GREEN: [number, number, number] = [22, 163, 74];

export type Classification = 'Clean' | 'Suspicious' | 'High Risk';

export interface ReportViolation {
  timestamp: string;
  type: string;
  description: string;
  severity: string;
}

export interface CandidateReportData {
  name: string;
  email: string;
  candidateId: string;
  assessmentTitle: string;
  assessmentDate: string;
  riskScore: number;
  integrityScore: number;
  classification: Classification;
  totalViolations: number;
  violations: ReportViolation[];
  aiSummary: string;
  conclusion: string;
  recommendation: string;
}

/* ─── Helpers ───────────────────────────────────────────────────────────────── */

async function loadLogo(): Promise<{ data: string; ratio: number } | null> {
  try {
    const res = await fetch(LOGO_URL);
    if (!res.ok) return null;
    const blob = await res.blob();
    const data = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
    const ratio = await new Promise<number>((resolve) => {
      const img = new Image();
      img.onload = () => resolve(img.naturalWidth && img.naturalHeight ? img.naturalWidth / img.naturalHeight : 1);
      img.onerror = () => resolve(1);
      img.src = data;
    });
    return { data, ratio };
  } catch {
    return null;
  }
}

function classificationColor(c: Classification): [number, number, number] {
  if (c === 'High Risk') return RED;
  if (c === 'Suspicious') return AMBER;
  return GREEN;
}

function severityColor(severity: string): [number, number, number] {
  const s = severity.toLowerCase();
  if (s === 'critical' || s === 'high') return RED;
  if (s === 'medium') return AMBER;
  return GREEN;
}

function prettyType(type: string): string {
  return type.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

/* ─── PDF assembly ──────────────────────────────────────────────────────────── */

const PAGE_MARGIN = 14;

function drawHeader(
  doc: jsPDF,
  logo: { data: string; ratio: number } | null,
  subtitle: string = SYSTEM_NAME,
): number {
  const pageW = doc.internal.pageSize.getWidth();
  const top = 12;

  // Navy banner.
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, 30, 'F');

  let textX = PAGE_MARGIN;
  if (logo) {
    const h = 14;
    const w = h * logo.ratio;
    try {
      doc.addImage(logo.data, 'PNG', PAGE_MARGIN, top - 5, w, h);
      textX = PAGE_MARGIN + w + 5;
    } catch {
      /* ignore image failures */
    }
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(COMPANY_NAME, textX, top + 2);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(190, 215, 245);
  doc.text(subtitle, textX, top + 9);

  return 38; // y position after header
}

function drawFooter(doc: jsPDF, generatedAt: string): void {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const total = doc.getNumberOfPages();

  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setDrawColor(...BLUE);
    doc.setLineWidth(0.3);
    doc.line(PAGE_MARGIN, pageH - 16, pageW - PAGE_MARGIN, pageH - 16);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...SLATE);
    doc.text(`Generated by SemanticGuard AI  ·  ${COMPANY_NAME}`, PAGE_MARGIN, pageH - 10);
    doc.text(`Report generated: ${generatedAt}`, PAGE_MARGIN, pageH - 6);
    doc.text(`Page ${i} of ${total}`, pageW - PAGE_MARGIN, pageH - 8, { align: 'right' });
  }
}

function sectionTitle(doc: jsPDF, text: string, y: number): number {
  doc.setFillColor(...BLUE);
  doc.rect(PAGE_MARGIN, y, 3, 5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...NAVY);
  doc.text(text, PAGE_MARGIN + 6, y + 4.3);
  return y + 10;
}

function labelValueRow(
  doc: jsPDF,
  pairs: [string, string][],
  y: number,
): number {
  const pageW = doc.internal.pageSize.getWidth();
  const colW = (pageW - PAGE_MARGIN * 2) / 2;
  let row = y;
  pairs.forEach((pair, i) => {
    const col = i % 2;
    const x = PAGE_MARGIN + col * colW;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...SLATE);
    doc.text(pair[0].toUpperCase(), x, row);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.text(pair[1] || '—', x, row + 5);
    if (col === 1 || i === pairs.length - 1) row += 13;
  });
  return row;
}

function renderCandidate(
  doc: jsPDF,
  c: CandidateReportData,
  logo: { data: string; ratio: number } | null,
): void {
  let y = drawHeader(doc, logo);

  // ── Candidate section ──────────────────────────────────────────────────────
  y = sectionTitle(doc, 'Candidate', y);
  y = labelValueRow(doc, [
    ['Full Name', c.name],
    ['Candidate ID', c.candidateId],
    ['Assessment', c.assessmentTitle],
    ['Email', c.email],
    ['Assessment Date / Time', c.assessmentDate],
    ['Status', c.classification],
  ], y);

  y += 2;

  // ── Integrity summary ──────────────────────────────────────────────────────
  y = sectionTitle(doc, 'Integrity Summary', y);

  const pageW = doc.internal.pageSize.getWidth();
  const cardW = (pageW - PAGE_MARGIN * 2 - 8) / 3;
  const cards: [string, string, [number, number, number]][] = [
    ['Total Violations', String(c.totalViolations), c.totalViolations > 0 ? RED : GREEN],
    ['Risk Score', `${Math.round(c.riskScore)}`, c.riskScore >= 70 ? RED : c.riskScore >= 40 ? AMBER : GREEN],
    ['Classification', c.classification, classificationColor(c.classification)],
  ];
  cards.forEach((card, i) => {
    const x = PAGE_MARGIN + i * (cardW + 4);
    doc.setFillColor(247, 249, 252);
    doc.roundedRect(x, y, cardW, 18, 1.5, 1.5, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...SLATE);
    doc.text(card[0].toUpperCase(), x + 4, y + 6);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(...card[2]);
    doc.text(card[1], x + 4, y + 14);
  });
  y += 25;

  // ── Violation details table ────────────────────────────────────────────────
  y = sectionTitle(doc, 'Violation Details', y);

  if (c.violations.length === 0) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(...SLATE);
    doc.text('No integrity violations were recorded for this session.', PAGE_MARGIN, y + 2);
    y += 10;
  } else {
    autoTable(doc, {
      startY: y,
      head: [['Timestamp', 'Violation Type', 'Description', 'Severity']],
      body: c.violations.map((v) => [
        v.timestamp,
        prettyType(v.type),
        v.description || '—',
        v.severity.toUpperCase(),
      ]),
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
      styles: { fontSize: 8, cellPadding: 2, overflow: 'linebreak', valign: 'middle' },
      headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', fontSize: 8 },
      alternateRowStyles: { fillColor: [247, 249, 252] },
      columnStyles: {
        0: { cellWidth: 36 },
        1: { cellWidth: 36 },
        2: { cellWidth: 'auto' },
        3: { cellWidth: 22, halign: 'center' },
      },
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 3) {
          data.cell.styles.textColor = severityColor(String(data.cell.raw));
          data.cell.styles.fontStyle = 'bold';
        }
      },
    });
    // @ts-expect-error - lastAutoTable is attached at runtime by jspdf-autotable.
    y = (doc.lastAutoTable?.finalY ?? y) + 8;
  }

  // ── AI analysis section ────────────────────────────────────────────────────
  const pageH = doc.internal.pageSize.getHeight();
  if (y > pageH - 70) {
    doc.addPage();
    y = drawHeader(doc, logo);
  }

  y = sectionTitle(doc, 'AI Analysis', y);
  const usableW = pageW - PAGE_MARGIN * 2;

  const block = (label: string, body: string, yy: number): number => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...NAVY);
    doc.text(label, PAGE_MARGIN, yy);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(55, 65, 81);
    const lines = doc.splitTextToSize(body || '—', usableW);
    doc.text(lines, PAGE_MARGIN, yy + 5);
    return yy + 5 + lines.length * 4.6 + 4;
  };

  y = block('Detected Behavior Summary', c.aiSummary, y);
  y = block('Integrity Conclusion', c.conclusion, y);
  block('Recommendation for Recruiter', c.recommendation, y);
}

/* ─── Public API ────────────────────────────────────────────────────────────── */

export async function generateIntegrityReport(
  candidates: CandidateReportData[],
  fileName = 'SemanticGuard-Integrity-Report.pdf',
): Promise<void> {
  if (candidates.length === 0) return;

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const logo = await loadLogo();
  const generatedAt = new Date().toLocaleString();

  candidates.forEach((c, i) => {
    if (i > 0) doc.addPage();
    renderCandidate(doc, c, logo);
  });

  drawFooter(doc, generatedAt);
  doc.save(fileName);
}

/* ════════════════════════════════════════════════════════════════════════════
 * Shared layout helpers reused by candidate & administrator reports.
 * ════════════════════════════════════════════════════════════════════════════ */

function ensureSpace(
  doc: jsPDF,
  y: number,
  needed: number,
  logo: { data: string; ratio: number } | null,
  subtitle: string,
): number {
  const pageH = doc.internal.pageSize.getHeight();
  if (y + needed > pageH - 22) {
    doc.addPage();
    return drawHeader(doc, logo, subtitle);
  }
  return y;
}

function reportTitle(doc: jsPDF, title: string, subtitle: string, y: number): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...NAVY);
  doc.text(title, PAGE_MARGIN, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...SLATE);
  doc.text(subtitle, PAGE_MARGIN, y + 6);
  return y + 14;
}

/** Render a row of summary "stat" cards. */
function statCards(
  doc: jsPDF,
  cards: { label: string; value: string; color?: [number, number, number] }[],
  y: number,
): number {
  const pageW = doc.internal.pageSize.getWidth();
  const gap = 4;
  const cardW = (pageW - PAGE_MARGIN * 2 - gap * (cards.length - 1)) / cards.length;
  cards.forEach((card, i) => {
    const x = PAGE_MARGIN + i * (cardW + gap);
    doc.setFillColor(247, 249, 252);
    doc.roundedRect(x, y, cardW, 18, 1.5, 1.5, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...SLATE);
    doc.text(card.label.toUpperCase(), x + 4, y + 6, { maxWidth: cardW - 8 });
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(...(card.color ?? NAVY));
    doc.text(card.value, x + 4, y + 14);
  });
  return y + 25;
}

function paragraph(doc: jsPDF, label: string, body: string, y: number): number {
  const pageW = doc.internal.pageSize.getWidth();
  const usableW = pageW - PAGE_MARGIN * 2;
  if (label) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...NAVY);
    doc.text(label, PAGE_MARGIN, y);
    y += 5;
  }
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81);
  const lines = doc.splitTextToSize(body || '—', usableW);
  doc.text(lines, PAGE_MARGIN, y);
  return y + lines.length * 4.6 + 4;
}

function lastTableY(doc: jsPDF, fallback: number): number {
  // @ts-expect-error - lastAutoTable is attached at runtime by jspdf-autotable.
  return (doc.lastAutoTable?.finalY ?? fallback) + 8;
}

/* ════════════════════════════════════════════════════════════════════════════
 * Candidate report — own assessment result + integrity summary.
 * ════════════════════════════════════════════════════════════════════════════ */

export interface CandidateResultReportData {
  candidateName: string;
  candidateId: string;
  assessmentTitle: string;
  assessmentDate: string;
  durationLabel: string;
  score: number;
  maxScore: number;
  percentage: number;
  passed: boolean | null;
  integrityScore: number;
  riskScore: number;
  riskLevel: string;
  tabSwitches: number;
  lookingAwayCount: number;
  faceNotDetectedCount: number;
  classification: Classification;
  violations: ReportViolation[];
  aiSummary: string;
}

export async function generateCandidateResultReport(
  data: CandidateResultReportData,
  fileName = 'SemanticGuard-Assessment-Result.pdf',
): Promise<void> {
  const subtitle = 'SemanticGuard AI Assessment Result';
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const logo = await loadLogo();
  const generatedAt = new Date().toLocaleString();

  let y = drawHeader(doc, logo, subtitle);
  y = reportTitle(doc, 'Assessment Result & Integrity Summary', data.assessmentTitle, y);

  // Candidate / assessment details.
  y = sectionTitle(doc, 'Candidate & Assessment', y);
  y = labelValueRow(doc, [
    ['Candidate Name', data.candidateName],
    ['Candidate ID', data.candidateId],
    ['Assessment', data.assessmentTitle],
    ['Date', data.assessmentDate],
    ['Duration', data.durationLabel],
    ['Outcome', data.passed == null ? '—' : data.passed ? 'Passed' : 'Did Not Pass'],
  ], y);
  y += 2;

  // Score & integrity cards.
  y = sectionTitle(doc, 'Performance & Integrity', y);
  y = statCards(doc, [
    { label: 'Final Score', value: `${Math.round(data.percentage)}%`, color: NAVY },
    {
      label: 'Integrity Score',
      value: `${Math.round(data.integrityScore)}`,
      color: data.integrityScore >= 80 ? GREEN : data.integrityScore >= 60 ? AMBER : RED,
    },
    {
      label: 'Risk Level',
      value: data.riskLevel.toUpperCase(),
      color: data.riskLevel === 'high' ? RED : data.riskLevel === 'medium' ? AMBER : GREEN,
    },
    {
      label: 'Classification',
      value: data.classification,
      color: classificationColor(data.classification),
    },
  ], y);

  // Monitoring counters.
  y = sectionTitle(doc, 'Monitoring Summary', y);
  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: [
      ['Raw Score', `${data.score} / ${data.maxScore}`],
      ['Tab Switches', String(data.tabSwitches)],
      ['Looking Away Events', String(data.lookingAwayCount)],
      ['Face Not Detected Events', String(data.faceNotDetectedCount)],
      ['Total Integrity Alerts', String(data.violations.length)],
      ['Aggregate Risk Score', String(Math.round(data.riskScore))],
    ],
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: { fontSize: 9, cellPadding: 2.4 },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', fontSize: 9 },
    alternateRowStyles: { fillColor: [247, 249, 252] },
    columnStyles: { 0: { cellWidth: 90 }, 1: { cellWidth: 'auto', fontStyle: 'bold' } },
  });
  y = lastTableY(doc, y);

  // Integrity events (if any).
  y = ensureSpace(doc, y, 40, logo, subtitle);
  y = sectionTitle(doc, 'Integrity Events', y);
  if (data.violations.length === 0) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(...SLATE);
    doc.text('No integrity violations were recorded during your assessment.', PAGE_MARGIN, y + 2);
    y += 10;
  } else {
    autoTable(doc, {
      startY: y,
      head: [['Timestamp', 'Event', 'Description', 'Severity']],
      body: data.violations.map((v) => [v.timestamp, prettyType(v.type), v.description || '—', v.severity.toUpperCase()]),
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
      styles: { fontSize: 8, cellPadding: 2, overflow: 'linebreak', valign: 'middle' },
      headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', fontSize: 8 },
      alternateRowStyles: { fillColor: [247, 249, 252] },
      columnStyles: { 0: { cellWidth: 34 }, 1: { cellWidth: 34 }, 2: { cellWidth: 'auto' }, 3: { cellWidth: 22, halign: 'center' } },
      didParseCell: (cell) => {
        if (cell.section === 'body' && cell.column.index === 3) {
          cell.cell.styles.textColor = severityColor(String(cell.cell.raw));
          cell.cell.styles.fontStyle = 'bold';
        }
      },
    });
    y = lastTableY(doc, y);
  }

  // AI summary.
  y = ensureSpace(doc, y, 30, logo, subtitle);
  y = sectionTitle(doc, 'AI Monitoring Summary', y);
  paragraph(doc, '', data.aiSummary, y);

  drawFooter(doc, generatedAt);
  doc.save(fileName);
}

/* ════════════════════════════════════════════════════════════════════════════
 * Administrator reports — audit, analytics, user directory, compliance.
 * ════════════════════════════════════════════════════════════════════════════ */

export interface AuditReportRow {
  timestamp: string;
  user: string;
  role: string;
  action: string;
  resource: string;
  ipAddress: string;
  status: string;
  details: string;
}

export async function generateAuditReport(
  rows: AuditReportRow[],
  meta: { total: number; success: number; failure: number; warning: number },
  fileName = 'SemanticGuard-Audit-Report.pdf',
): Promise<void> {
  const subtitle = 'SemanticGuard AI System Audit Report';
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' });
  const logo = await loadLogo();
  const generatedAt = new Date().toLocaleString();

  let y = drawHeader(doc, logo, subtitle);
  y = reportTitle(doc, 'System-Wide Audit Trail', `${rows.length} audit records included`, y);

  y = statCards(doc, [
    { label: 'Total Records', value: String(meta.total), color: NAVY },
    { label: 'Successful', value: String(meta.success), color: GREEN },
    { label: 'Failures', value: String(meta.failure), color: RED },
    { label: 'Warnings', value: String(meta.warning), color: AMBER },
  ], y);

  y = sectionTitle(doc, 'Audit Records', y);
  autoTable(doc, {
    startY: y,
    head: [['Timestamp', 'User', 'Role', 'Action', 'Resource', 'IP Address', 'Status', 'Details']],
    body: rows.map((r) => [
      r.timestamp, r.user, r.role, r.action.replace(/_/g, ' '),
      r.resource || '—', r.ipAddress || '—', r.status.toUpperCase(), r.details || '—',
    ]),
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: { fontSize: 7.5, cellPadding: 1.6, overflow: 'linebreak', valign: 'middle' },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', fontSize: 7.5 },
    alternateRowStyles: { fillColor: [247, 249, 252] },
    columnStyles: {
      0: { cellWidth: 34 }, 1: { cellWidth: 40 }, 2: { cellWidth: 20 },
      3: { cellWidth: 32 }, 4: { cellWidth: 32 }, 5: { cellWidth: 26 },
      6: { cellWidth: 20, halign: 'center' }, 7: { cellWidth: 'auto' },
    },
    didParseCell: (cell) => {
      if (cell.section === 'body' && cell.column.index === 6) {
        const v = String(cell.cell.raw).toLowerCase();
        cell.cell.styles.textColor = v === 'failure' ? RED : v === 'warning' ? AMBER : GREEN;
        cell.cell.styles.fontStyle = 'bold';
      }
    },
  });

  drawFooter(doc, generatedAt);
  doc.save(fileName);
}

export interface AnalyticsReportData {
  kpis: { label: string; value: string }[];
  monthly: { month: string; assessments: number; incidents: number; candidates: number }[];
  riskDistribution: { name: string; value: number }[];
  performance: { month: string; avgScore: number; avgIntegrity: number }[];
}

export async function generateAnalyticsReport(
  data: AnalyticsReportData,
  fileName = 'SemanticGuard-Analytics-Report.pdf',
): Promise<void> {
  const subtitle = 'SemanticGuard AI Analytics Report';
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const logo = await loadLogo();
  const generatedAt = new Date().toLocaleString();

  let y = drawHeader(doc, logo, subtitle);
  y = reportTitle(doc, 'Organization-Wide Analytics', 'Recruitment integrity & performance overview', y);

  y = statCards(doc, data.kpis.slice(0, 4).map((k) => ({ label: k.label, value: k.value })), y);

  y = sectionTitle(doc, 'Monthly Assessments & Incidents', y);
  autoTable(doc, {
    startY: y,
    head: [['Month', 'Assessments', 'Candidates', 'Incidents']],
    body: data.monthly.map((m) => [m.month, String(m.assessments), String(m.candidates), String(m.incidents)]),
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: { fontSize: 9, cellPadding: 2.2 },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', fontSize: 9 },
    alternateRowStyles: { fillColor: [247, 249, 252] },
  });
  y = lastTableY(doc, y);

  y = ensureSpace(doc, y, 50, logo, subtitle);
  y = sectionTitle(doc, 'Candidate Performance Trend', y);
  autoTable(doc, {
    startY: y,
    head: [['Month', 'Avg Score (%)', 'Avg Integrity']],
    body: data.performance.map((p) => [p.month, String(p.avgScore), String(p.avgIntegrity)]),
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: { fontSize: 9, cellPadding: 2.2 },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', fontSize: 9 },
    alternateRowStyles: { fillColor: [247, 249, 252] },
  });
  y = lastTableY(doc, y);

  y = ensureSpace(doc, y, 40, logo, subtitle);
  y = sectionTitle(doc, 'Risk Distribution', y);
  if (data.riskDistribution.length === 0) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(...SLATE);
    doc.text('No completed sessions available for risk distribution.', PAGE_MARGIN, y + 2);
  } else {
    autoTable(doc, {
      startY: y,
      head: [['Risk Level', 'Candidates']],
      body: data.riskDistribution.map((r) => [r.name, String(r.value)]),
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
      styles: { fontSize: 9, cellPadding: 2.2 },
      headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', fontSize: 9 },
      alternateRowStyles: { fillColor: [247, 249, 252] },
      columnStyles: { 0: { cellWidth: 90 }, 1: { cellWidth: 'auto', fontStyle: 'bold' } },
    });
  }

  drawFooter(doc, generatedAt);
  doc.save(fileName);
}

export interface UserDirectoryRow {
  name: string;
  email: string;
  role: string;
  status: string;
  department: string;
  createdAt: string;
  lastLogin: string;
}

export async function generateUserDirectoryReport(
  rows: UserDirectoryRow[],
  meta: { total: number; candidates: number; recruiters: number; admins: number },
  fileName = 'SemanticGuard-User-Directory.pdf',
): Promise<void> {
  const subtitle = 'SemanticGuard AI User Directory';
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' });
  const logo = await loadLogo();
  const generatedAt = new Date().toLocaleString();

  let y = drawHeader(doc, logo, subtitle);
  y = reportTitle(doc, 'System User Directory', `${rows.length} user accounts`, y);

  y = statCards(doc, [
    { label: 'Total Users', value: String(meta.total), color: NAVY },
    { label: 'Candidates', value: String(meta.candidates), color: BLUE },
    { label: 'Recruiters', value: String(meta.recruiters), color: AMBER },
    { label: 'Administrators', value: String(meta.admins), color: NAVY },
  ], y);

  y = sectionTitle(doc, 'All Users', y);
  autoTable(doc, {
    startY: y,
    head: [['Name', 'Email', 'Role', 'Status', 'Department', 'Created', 'Last Login']],
    body: rows.map((r) => [
      r.name, r.email, r.role.toUpperCase(), r.status.toUpperCase(),
      r.department || '—', r.createdAt, r.lastLogin,
    ]),
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: { fontSize: 8, cellPadding: 1.8, overflow: 'linebreak', valign: 'middle' },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', fontSize: 8 },
    alternateRowStyles: { fillColor: [247, 249, 252] },
    columnStyles: {
      0: { cellWidth: 44 }, 1: { cellWidth: 60 }, 2: { cellWidth: 24 },
      3: { cellWidth: 24 }, 4: { cellWidth: 36 }, 5: { cellWidth: 32 }, 6: { cellWidth: 'auto' },
    },
    didParseCell: (cell) => {
      if (cell.section === 'body' && cell.column.index === 3) {
        const v = String(cell.cell.raw).toLowerCase();
        cell.cell.styles.textColor = v === 'suspended' ? RED : v === 'active' ? GREEN : SLATE;
        cell.cell.styles.fontStyle = 'bold';
      }
    },
  });

  drawFooter(doc, generatedAt);
  doc.save(fileName);
}

export interface ComplianceReportData {
  totalUsers: number;
  activeUsers: number;
  suspendedUsers: number;
  mfaEnabled: number;
  totalAssessments: number;
  totalSessions: number;
  flaggedSessions: number;
  totalAlerts: number;
  unreviewedAlerts: number;
  avgIntegrity: number;
  auditTotal: number;
  auditFailures: number;
}

export async function generateComplianceReport(
  data: ComplianceReportData,
  fileName = 'SemanticGuard-Compliance-Summary.pdf',
): Promise<void> {
  const subtitle = 'SemanticGuard AI Compliance Summary';
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const logo = await loadLogo();
  const generatedAt = new Date().toLocaleString();

  let y = drawHeader(doc, logo, subtitle);
  y = reportTitle(doc, 'Compliance & Governance Summary', 'Platform-wide integrity & security posture', y);

  const mfaPct = data.totalUsers ? Math.round((data.mfaEnabled / data.totalUsers) * 100) : 0;
  const flaggedPct = data.totalSessions ? Math.round((data.flaggedSessions / data.totalSessions) * 100) : 0;
  const reviewedPct = data.totalAlerts ? Math.round(((data.totalAlerts - data.unreviewedAlerts) / data.totalAlerts) * 100) : 100;

  y = statCards(doc, [
    { label: 'Total Users', value: String(data.totalUsers), color: NAVY },
    { label: 'MFA Coverage', value: `${mfaPct}%`, color: mfaPct >= 80 ? GREEN : mfaPct >= 50 ? AMBER : RED },
    { label: 'Avg Integrity', value: String(data.avgIntegrity), color: data.avgIntegrity >= 80 ? GREEN : AMBER },
    { label: 'Alert Review Rate', value: `${reviewedPct}%`, color: reviewedPct >= 80 ? GREEN : AMBER },
  ], y);

  y = sectionTitle(doc, 'Access & Identity', y);
  autoTable(doc, {
    startY: y,
    head: [['Control', 'Value', 'Status']],
    body: [
      ['Total user accounts', String(data.totalUsers), 'Tracked'],
      ['Active accounts', String(data.activeUsers), 'OK'],
      ['Suspended accounts', String(data.suspendedUsers), data.suspendedUsers > 0 ? 'Review' : 'OK'],
      ['Multi-factor authentication coverage', `${mfaPct}%`, mfaPct >= 80 ? 'Compliant' : 'Action Needed'],
    ],
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: { fontSize: 9, cellPadding: 2.2 },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', fontSize: 9 },
    alternateRowStyles: { fillColor: [247, 249, 252] },
    columnStyles: { 0: { cellWidth: 'auto' }, 1: { cellWidth: 36, halign: 'center' }, 2: { cellWidth: 40, halign: 'center' } },
  });
  y = lastTableY(doc, y);

  y = ensureSpace(doc, y, 50, logo, subtitle);
  y = sectionTitle(doc, 'Assessment Integrity', y);
  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value', 'Status']],
    body: [
      ['Total assessments', String(data.totalAssessments), 'Tracked'],
      ['Total candidate sessions', String(data.totalSessions), 'Tracked'],
      ['Flagged sessions', `${data.flaggedSessions} (${flaggedPct}%)`, data.flaggedSessions > 0 ? 'Review' : 'OK'],
      ['Total integrity alerts', String(data.totalAlerts), 'Tracked'],
      ['Unreviewed alerts', String(data.unreviewedAlerts), data.unreviewedAlerts > 0 ? 'Action Needed' : 'OK'],
      ['Average integrity score', String(data.avgIntegrity), data.avgIntegrity >= 80 ? 'Healthy' : 'Monitor'],
    ],
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: { fontSize: 9, cellPadding: 2.2 },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', fontSize: 9 },
    alternateRowStyles: { fillColor: [247, 249, 252] },
    columnStyles: { 0: { cellWidth: 'auto' }, 1: { cellWidth: 36, halign: 'center' }, 2: { cellWidth: 40, halign: 'center' } },
  });
  y = lastTableY(doc, y);

  y = ensureSpace(doc, y, 36, logo, subtitle);
  y = sectionTitle(doc, 'Audit Trail', y);
  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: [
      ['Total audit records', String(data.auditTotal)],
      ['Failed / denied actions', String(data.auditFailures)],
    ],
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: { fontSize: 9, cellPadding: 2.2 },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', fontSize: 9 },
    alternateRowStyles: { fillColor: [247, 249, 252] },
    columnStyles: { 0: { cellWidth: 'auto' }, 1: { cellWidth: 40, halign: 'center', fontStyle: 'bold' } },
  });

  drawFooter(doc, generatedAt);
  doc.save(fileName);
}
