"""add email mfa fields

Revision ID: 235aa82d3cae
Revises: cdce4647d1ec
Create Date: 2026-06-16 15:20:54.472708
"""
from alembic import op
import sqlalchemy as sa
import app.models.base


revision = '235aa82d3cae'
down_revision = 'cdce4647d1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_method', sa.String(length=10), server_default='totp', nullable=False))
        batch_op.add_column(sa.Column('email_otp_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email_otp_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_otp_expires_at')
        batch_op.drop_column('email_otp_hash')
        batch_op.drop_column('mfa_method')

    # ### end Alembic commands ###
